apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlpage-index
spec:
  replicas: 2
  selector: 
    matchLabels:
       app: htmlpage
  template:
    metadata:
       labels:
         app: htmlpage
    spec:
      containers:
        - name: index
          image: indeximage
          ports:
            - containerPort: 80